### PR TITLE
Split up ES and health inputs, fix calculations, and also split up it…

### LINKED ISSUE #82: Make all name fields into selectors to autocomplete items by category
It would be nice to divide the items list into real sections, so each section's name box also functioned like quick add for its own types, but quick add still had access to all of them.

### LINKED ISSUE #85: MoM ignores damage absorbed by ES
From the mitigation site:

Taking the final damage:
* Non-chaos damage damages energy shield protecting life until it's depleted, by default.
* For Mind over Matter users, #% of the **remaining** damage is removed from mana. Mind over Matter only applies if the hit is damaging life.

We need to separate out ES and life for this.

### LINKED ISSUE #88: Lightning Coil (legacy) preset converts to chaos damage instead of lightning

### PR DESCRIPTION
**Pull request by ficocelliguy**
…ems into sections. Fixes #88, fixes #85

### CODE REVIEW

File: js/DataService.js [hunk 1]
```diff
@@ -125,7 +125,8 @@ angular.module('PathOfDamage')
         mitigation: {
           name: "Damage Mitigation",
           description: "Elemental and chaos damage is mitigated by its respective resistance. Physical damage is mitigated by the sum of all '% additional Physical Damage Reduction' modifiers, up to its 90% cap. This includes armor, endurance charges, and things like Basalt Flasks and Chaos Golem.",
-          healthPool: 5000,
+          health: 5000,
+          es: 0,
           manaPool: 1000,
```
Comment (PsychicMuffin) [inline js/DataService.js]: probably should just change this to mana to be consistent

File: js/Items.js [hunk 2]
```diff
@@ -2,38 +2,55 @@ angular.module('PathOfDamage')
 .service('Items', function () {
   return {
     getItems: function () {
-      return [
-        // Monster Modifications
+      return sort(
+          this.getMobModifiers()
```
Comment (PsychicMuffin) [inline js/Items.js:6]: I grouped mob modifiers for convenience earlier, but now we'll need monster increased and monster more to be separate

File: js/app.js [hunk 3]
```diff
@@ -177,37 +177,57 @@ angular.module('PathOfDamage', ['ui.select'])
...
 
   $scope.getMaximumSurvivableHit = function () {
     var hit = 0;
-    var start = Math.round(Math.log10($scope.sections.mitigation.healthPool)) + 1;
+    var calc = calcDamage(hit);
+    var start = Math.round(Math.log10($scope.sections.mitigation.health + $scope.sections.mitigation.es)) - 1;
     for (var i = start; i > -1; i--){
-      while (calcDamage(hit).remaining > 0) {
+      var l = 0;
+      while (calc.healthRemaining + calc.esRemaining > 0 && l++ < 1000) {
```
Comment (PsychicMuffin) [inline js/app.js]: this will bug out when we implement taking damage of all types, which will cause chaos damage to bypass ES without a certain flag set. Although I guess the max survivable hit is always physical for now, you get the idea, it can just be health remaining instead of both.

File: js/app.js [hunk 4]
```diff
@@ -177,37 +177,57 @@ angular.module('PathOfDamage', ['ui.select'])
...
   }
 
   $scope.getMaximumSurvivableHit = function () {
     var hit = 0;
-    var start = Math.round(Math.log10($scope.sections.mitigation.healthPool)) + 1;
+    var calc = calcDamage(hit);
+    var start = Math.round(Math.log10($scope.sections.mitigation.health + $scope.sections.mitigation.es)) - 1;
     for (var i = start; i > -1; i--){
-      while (calcDamage(hit).remaining > 0) {
+      var l = 0;
```
Comment (PsychicMuffin) [inline js/app.js]: I know this doesn't apply to JS scope, but shouldn't we place l outside the loop to be clear about its scope? Also, could we name it maxCalcs or something so its purpose is clearer?

File: js/Items.js [hunk 5]
```diff
@@ -2,38 +2,55 @@ angular.module('PathOfDamage')
 .service('Items', function () {
   return {
     getItems: function () {
-      return [
-        // Monster Modifications
+      return sort(
```
Comment (PsychicMuffin) [inline js/Items.js:5]: The point of splitting this up was for each section to function like quick add of its own category. We should either add that to this pull request or not mark the issue fixed.

**Review by PsychicMuffin — CHANGES_REQUESTED** [review]

File: js/Items.js (hunk 5 above)
Comment (ficocelliguy) [reply js/Items.js:5]: //TODO

File: js/Items.js (hunk 2 above)
Comment (ficocelliguy) [reply js/Items.js:6]: //TODO

**Review by PsychicMuffin — APPROVED** [review]
